import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './overrides.css';

const projects = [
  { id: 'smallball', number: '01', kind: 'Produit métier', title: 'Small Ball Academy', intro: 'Application pour aider les coachs à gérer leurs exercices, préparer leurs séances et structurer une bibliothèque pédagogique réutilisable.', tags: ['React', 'TypeScript', 'Django REST', 'Netlify'], result: 'Un MVP SaaS métier complet : bibliothèque d’exercices, composition de séance, sauvegarde locale et export imprimable.', accent: 'orange', context: 'Les coachs préparent souvent leurs séances avec des notes dispersées et des exercices difficiles à réutiliser.', problem: 'Gagner du temps tout en gardant une logique pédagogique claire.', solution: 'Une application terrain centrée sur la bibliothèque d’exercices et la fiche de séance imprimable.', details: ['Bibliothèque de 26 exercices filtrables', 'Composition par âge, durée, thème et effectif', 'Fiche A4 responsive et sauvegarde locale', 'Fondation Django REST préparée, synchronisation volontaire'], stack: 'React, Vite, TypeScript, Django REST préparé, Netlify', state: 'Prototype fonctionnel en staging, en phase de test privé.', note: 'Le backend Django REST est préparé pour l’évolution SaaS. La version actuellement visible reste centrée sur le parcours utilisateur et la validation fonctionnelle.', screenshots: ['/screenshots/smallball-home.png', '/screenshots/smallball-session.png', '/screenshots/smallball-library.png'] },
  { id: 'nomeeting', number: '02', kind: 'Outil collaboratif', title: 'NoMeeting', intro: 'Outil collaboratif pour centraliser les décisions, clarifier les priorités et réduire les échanges inutiles.', tags: ['React', 'Supabase', 'Realtime'], result: 'Une coordination légère autour des priorités, blocages et disponibilités.', accent: 'blue', context: 'Les équipes perdent du temps quand les décisions, priorités et responsabilités restent dispersées.', problem: 'Créer un espace plus calme pour suivre les actions et les informations utiles.', solution: 'Un outil collaboratif léger qui rend les statuts, priorités et blocages visibles au même endroit.', details: ['Espaces de travail et invitations de guests', 'Priorités, statuts et présence en temps réel', 'Responsive mobile et gestion des paramètres', 'Accès authentifié et règles de sécurité Supabase'], stack: 'React, TypeScript, Supabase, Realtime, Netlify', state: 'Prototype produit en évolution.', note: 'Le projet démontre ma capacité à concevoir un outil collaboratif simple, avec logique temps réel, gestion des accès et interface centrée sur la réduction du bruit.', screenshots: ['/screenshots/nomeeting-dashboard.png', '/screenshots/nomeeting-member-settings.png'] },
  { id: 'skolapp', number: '03', kind: 'Application métier', title: 'Skolapp', intro: 'Application métier pour structurer un service sportif/scolaire, gérer les données clés et tester un parcours utilisateur complet.', tags: ['Python', 'Django', 'React'], result: 'Une base applicative pour clarifier les rôles, structurer les flux métier et préparer les itérations suivantes.', accent: 'purple', context: 'Le besoin était de structurer un parcours logiciel autour d’un service sportif ou scolaire.', problem: 'Passer d’une idée de service à une application métier testable.', solution: 'Une application web pensée autour des données principales et d’un parcours utilisateur structuré.', details: ['Modélisation des rôles et des parcours', 'Backend Python/Django et interface React', 'Structure de données métier', 'Approche MVP : livrer le flux critique d’abord'], stack: 'Python, Django, React', state: 'Projet métier ayant servi à structurer une première approche complète : modélisation des rôles, parcours utilisateur, backend Django et interface React.', note: 'Projet présenté comme preuve de modélisation métier et de construction full-stack.' }
];

function App() {
  const [active, setActive] = useState(null);
  const [menu, setMenu] = useState(false);
  const selected = projects.find((p) => p.id === active);
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenu(false); };
  return <>
    <header className="nav wrap">
      <button className="brand" onClick={() => scrollTo('top')}><span className="brand-mark">EJ</span><span>Étienne Jonckers</span></button>
      <button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Ouvrir le menu">☰</button>
      <nav className={menu ? 'nav-links open' : 'nav-links'}><button onClick={() => scrollTo('services')}>Services</button><button onClick={() => scrollTo('work')}>Réalisations</button><button onClick={() => scrollTo('about')}>À propos</button><button className="nav-cta" onClick={() => scrollTo('contact')}>Parlons de votre projet <span>↗</span></button></nav>
    </header>
    <main id="top">
      <section className="hero wrap">
        <div className="hero-copy"><p className="eyebrow"><i></i> Disponible pour une mission ciblée</p><h1>Je transforme les idées floues en <em>outils qui servent</em> vraiment.</h1><p className="hero-text">Développeur full-stack Python / React, j’aide les petites équipes à transformer un besoin métier en MVP, outil interne, dashboard ou automatisation utile.</p><div className="hero-actions"><button className="button primary" onClick={() => scrollTo('contact')}>Expliquer votre besoin <span>↗</span></button><button className="text-link" onClick={() => scrollTo('work')}>Voir les réalisations <span>↓</span></button></div></div>
        <div className="hero-card"><div className="card-top"><span className="status-dot"></span><span>focus du moment</span><span className="card-count">01 / 03</span></div><div className="orbit"><div className="orbit-line one"></div><div className="orbit-line two"></div><div className="orbit-core">IA<br/><small>appliquée</small></div><span className="orbit-tag tag-one">Python</span><span className="orbit-tag tag-two">Produit</span><span className="orbit-tag tag-three">React</span></div><p className="card-caption">La technologie reste au service du problème. Sinon, c’est juste un très joli marteau.</p></div>
      </section>
      <div className="trust-strip"><div className="wrap trust-inner"><span>Ce que je construis</span><strong>MVPs utiles</strong><strong>Outils internes</strong><strong>Dashboards</strong><strong>Automatisations</strong><strong>Intégrations IA</strong></div></div>
      <section className="section wrap" id="services"><div className="section-heading"><p className="eyebrow">01 — Comment je peux aider</p><h2>Un renfort technique, avec une vision produit.</h2><p>Vous n’avez pas besoin d’un système trop lourd. Vous avez besoin du bon flux, bien construit, puis amélioré avec les vrais retours.</p></div><div className="service-grid"><article><span className="service-icon">↗</span><h3>MVP & produit</h3><p>Du besoin prioritaire à une première version utilisable, avec un périmètre clair et une base qui tient debout.</p><a onClick={() => scrollTo('contact')}>Démarrer simplement <span>→</span></a></article><article><span className="service-icon">▦</span><h3>Outils & dashboards</h3><p>Des interfaces qui rendent une opération plus claire : données, statuts, décisions et actions.</p><a onClick={() => scrollTo('contact')}>Clarifier un flux <span>→</span></a></article><article><span className="service-icon">✦</span><h3>Automatisation & IA</h3><p>Connecter les bons outils et ajouter de l’IA là où elle fait gagner du temps — sans gadget.</p><a onClick={() => scrollTo('contact')}>Explorer une idée <span>→</span></a></article></div></section>
      <section className="available wrap"><div><p className="eyebrow">Mission type</p><h2>Disponible pour des missions concrètes.</h2><p>J’interviens sur des besoins ciblés où une première version utile vaut mieux qu’un grand système théorique.</p></div><div className="available-grid">{['MVP SaaS ou prototype web','Outil interne métier','Dashboard sur données existantes','Automatisation de processus manuel','Backend Django / FastAPI','Frontend React / TypeScript','IA utile : résumé, extraction, classification ou RAG léger'].map(item => <span key={item}><i>+</i>{item}</span>)}</div><p className="fit-note"><b>Bon cadrage :</b> je suis surtout utile sur des missions ciblées, avec un besoin métier à clarifier, un MVP à lancer, un outil interne à structurer ou un flux à automatiser.</p></section>
      <section className="work-section" id="work"><div className="wrap"><div className="section-heading row"><div><p className="eyebrow">02 — Réalisations sélectionnées</p><h2>Des projets complets,<br/>pas seulement des écrans.</h2></div><p>Chaque projet part d’un usage concret : préparer, coordonner, décider ou faire circuler l’information.</p></div><div className="project-list">{projects.map((p) => <button className="project-row" key={p.id} onClick={() => setActive(p.id)}><span className={`project-index ${p.accent}`}>{p.number}</span><span className="project-main"><small>{p.kind}</small><strong>{p.title}</strong><span>{p.intro}</span></span><span className="project-tags">{p.tags.map(t => <b key={t}>{t}</b>)}</span><span className="arrow">↗</span></button>)}</div></div></section>
      <section className="about wrap" id="about"><div className="about-quote"><p className="eyebrow">03 — À propos</p><blockquote>« Un bon produit ne fait pas tout. Il rend la prochaine bonne décision plus facile. »</blockquote></div><div className="about-copy"><p>Je suis Étienne Jonckers, développeur full-stack basé en Belgique. Mon parcours combine terrain métier, développement web et culture produit.</p><p>Avant de coder, je cherche à comprendre le flux réel : qui fait quoi, où le temps se perd, quelles données sont utiles, et quelle première version peut déjà apporter de la valeur.</p><p>Je travaille principalement avec Python, Django/FastAPI, React/TypeScript et PostgreSQL, avec un intérêt fort pour l’IA appliquée aux usages concrets.</p><div className="principles"><span><b>01</b> Écouter avant de coder</span><span><b>02</b> Livrer par petits incréments</span><span><b>03</b> Documenter les limites</span></div></div></section>
      <section className="contact-section" id="contact"><div className="wrap contact-box"><div><p className="eyebrow light">04 — Un projet en tête ?</p><h2>Commençons par le problème,<br/><em>pas par la technologie.</em></h2></div><div className="contact-action"><p>Expliquez-moi ce qui vous ralentit aujourd’hui. Même en quelques lignes, c’est suffisant pour un premier échange.</p><p className="availability-note">Disponible pour missions courtes ou moyennes.</p><a className="button light-button" href="mailto:jcksystems@icloud.com?subject=Parlons de mon projet">M’expliquer votre besoin <span>↗</span></a><div className="contact-socials"><a href="https://www.linkedin.com/in/etiennejonckers/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/Etiennejck" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></div></section>
    </main>
    <footer className="footer wrap"><span>© 2026 Étienne Jonckers</span><span>Python · React · IA appliquée</span><a href="mailto:etienne.jonckers@gmail.com">etienne.jonckers@gmail.com</a></footer>
    {selected && <div className="modal-backdrop" onClick={() => setActive(null)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setActive(null)}>×</button><p className={`eyebrow ${selected.accent}`}>{selected.number} — {selected.kind}</p><h2>{selected.title}</h2><p className="modal-intro">{selected.intro}</p><div className="product-preview"><small>Aperçu du produit</small><div className="preview-grid">{(selected.screenshots || [null]).slice(0, 2).map((src, index) => src ? <img key={src} src={src} alt={`Capture de ${selected.title} ${index + 1}`} /> : <div className="preview-placeholder" key="placeholder"><span>＋</span>Capture produit à ajouter</div>)}</div></div><div className="case-grid"><div><small>Contexte</small><p>{selected.context}</p></div><div><small>Problème</small><p>{selected.problem}</p></div><div><small>Solution</small><p>{selected.solution}</p></div><div><small>État actuel</small><p>{selected.state}</p></div></div><div className="modal-result"><small>Ce que le projet démontre</small><strong>{selected.result}</strong></div><h4>Ce que j’ai construit</h4><ul>{selected.details.map(d => <li key={d}>{d}</li>)}</ul><p className="stack-line"><b>Stack :</b> {selected.stack}</p><p className="modal-note">{selected.note}</p>{selected.id !== 'skolapp' && <a className="modal-link" href={selected.id === 'nomeeting' ? 'https://nomeeting-jck.netlify.app' : 'https://staging--small-ball-academy-v0.netlify.app'} target="_blank" rel="noreferrer">Voir le projet en ligne <span>↗</span></a>}</div></div>}
  </>;
}
createRoot(document.getElementById('root')).render(<App />);
